# SonarQube configuration for .NET application (built with .NET Framework 4.8) 

# Define the workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarqube:
    name: SonarQube Analysis
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better relevancy of analysis

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'  # Adjust the Java version as per your requirements

      - name: Download .NET Framework 4.8 Installer
        run: |
         $url = "https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net48-web-installer"
         $response = Invoke-WebRequest -Uri $url -Method Get
         $link = $response.Links | Where-Object { $_.innerText -eq "Download .NET Framework 4.8 Runtime" }
         $downloadUrl = $link.href
         $installerPath = "$env:TEMP\ndp48-web.exe"
         Invoke-WebRequest -Uri $downloadUrl -OutFile $installerPath

      - name: Install .NET Framework 4.8
        run: |
         Start-Process -FilePath "$env:TEMP\ndp48-web.exe" -ArgumentList '/q' -Wait
      - name: SonarQube Scan
        run: |
          dotnet tool install --global dotnet-sonarscanner 
          dotnet-sonarscanner begin /k:"dotnet1_sim" /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.cache.enabled=true /d:sonar.cache.path="D:\a\sonarqube_cache"
          msbuild /t:Rebuild
          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
