# SonarQube configuration for Java and .NET applications
# Replace the placeholders with your actual values

# Define the workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: SonarQube Scan (Java)
        uses: sonarsource/sonarqube-scan-action@v1
        with:
          projectBaseDir: ./java-app

          # SonarQube token for authentication
          sonarToken: ${{ secrets.SONAR_TOKEN }}

          # SonarQube host URL
          sonarHost: ${{ secrets.SONAR_HOST_URL }}

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: SonarQube Scan (.NET)
        uses: sonarsource/sonarqube-scan-action@v1
        with:
          projectBaseDir: ./dotnet-app

          # SonarQube token for authentication
          sonarToken: ${{ secrets.SONAR_TOKEN }}

          # SonarQube host URL
          sonarHost: ${{ secrets.SONAR_HOST_URL }}
